language: ruby
rvm:
- 2.0.0-p481
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: k0CtcgzHvDW/4Bi38x05utgHQT3fJfIfnm/jJqqJE+8oNuY0kCdP8pfzil7NPVwvFJ2vKOyVVfYBllTAolok52/ERcU4RYTns580yubwSPrsJE/omCvRZ+AAdnJSU5cs9uYP2c2k/n9MqkrXRXB48tL97MKZpEnghn4vMD1iluk=
app: sleepy-forest-7490
run:
    #remember that migrations you run locally must run in the release environment
    - "rake db:migrate"
    - restart